spring.application.name: product-service
server.port: 8383
logging.level.root: debug
#eureka.client.service-url.defaultZone: http://localhost:8761/eureka/
eureka.client.service-url.defaultZone: http://service-registry:8761/eureka/
spring.zipkin.base-url: http://zipkin:9411/
spring.sleuth.sampler.probability: 1