spring.application.name: inventory-service
server.port: 8282
logging.level.root: debug
#eureka.client.service-url.defaultZone: http://service-registry:8761/eureka/
eureka.client.service-url.defaultZone: http://localhost:8761/eureka/
csv.file.name: jcpenney_com-ecommerce_sample.csv
spring.zipkin.base-url: http://zipkin:9411/
spring.sleuth.sampler.probability: 1